<a href="https://colab.research.google.com/github/beyzassevval/Techcareer_VeriBilimi_Odevlerim/blob/main/%C3%96dev_3_ilk_k%C4%B1s%C4%B1m.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Haftalık Ödev – Yaz Kampı: Veri Bilimi – Hafta 3

In [3]:
# Soru 1 : Liste metodları
notlar=[85, 92, 76, 92, 100, 76, 85, 92]
#tekrar eden notları sil
notlar=list(set(notlar))
print("Benzersiz Liste:",notlar)
#en yüksek ve en düşük not
print("En Yüksek Not:",max(notlar))
print("En Düşük Not:",min(notlar))
#notları küçükten büyüğe sırala
print("Küçükten Büyüge sıralı:",sorted(notlar))

Benzersiz Liste: [100, 92, 85, 76]
En Yüksek Not: 100
En Düşük Not: 76
Küçükten Büyüge sıralı: [76, 85, 92, 100]


In [8]:
#Soru 2 – Sayılar
# Armstrong sayı mı?
#Armstrong sayısı: Her basamağının küplerinin toplamı kendisine eşit olan sayılar.
def is_armstrong(n: int) -> bool:
    digits = [int(d) for d in str(n)]
    # Küplerinin toplamını al
    total = sum([d**3 for d in digits])
    # Kontrol
    return total == n

# Test
print(is_armstrong(153))  # True
print(is_armstrong(370))  # True
print(is_armstrong(371))  # True
print(is_armstrong(9474)) # False, çünkü 3 basamaklı sayılara göre kod yazdım
print(is_armstrong(123))  # False




True
True
True
False
False


In [2]:
#Soru 3 – Kümeler
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
#iki kümede ortak diller neler bulalım
print("Ortak Özellikler:")
set.intersection(A,B)
#Sadece A da olanlar
print("Sadece A da olanlar:")
set.difference(A,B)
#Sadece B de olanlar
print("Sadece B de olanlar:")
set.difference(B,A)
#iki kümenin birleşimi
print("İki kümenin birleşimi:")
set.union(A,B)


Ortak Özellikler:
Sadece A da olanlar:
Sadece B de olanlar:
İki kümenin birleşimi:


{'C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL'}

In [5]:
#Soru 4 – Modüller
import random
import statistics

sayilar = random.sample(range(1, 101), 10)
print("Rastgele Sayılar:", sayilar)

#ortalama
ortalama = statistics.mean(sayilar)
print("Ortalama:", ortalama)

#standart sapma
standart_sapma = statistics.stdev(sayilar)
print("Standart Sapma:", standart_sapma)

Rastgele Sayılar: [11, 71, 21, 9, 90, 65, 99, 79, 20, 58]
Ortalama: 52.3
Standart Sapma: 34.09480247127934


In [14]:
#Soru 5 – Fonksiyonlar
metin='''Veri bilimi, yapılandırılmış ve yapılandırılmamış verilerden bilgi ve öngörü elde etmek için bilimsel yöntemleri,
süreçleri, algoritmaları ve sistemleri kullanan çok disiplinli bir alandır.
Veri bilimi veri madenciliği ve büyük verilerle ilişkilidir.'''

def kelime_sayaci(metin):
    kelimeler = metin.split()
    toplam_kelime_sayisi = len(kelimeler)
    en_uzun_kelime = max(kelimeler, key=len)
    en_cok_gecen_kelime = max(set(kelimeler), key=kelimeler.count)

    print("Toplam kelime sayısı:", toplam_kelime_sayisi)
    print("En uzun kelime:", en_uzun_kelime)
    print("En sık geçen kelime:", en_cok_gecen_kelime)

kelime_sayaci(metin)


Toplam kelime sayısı: 31
En uzun kelime: yapılandırılmamış
En sık geçen kelime: ve


In [16]:
#Soru 6 – Gömülü Fonksiyonlar
#Aşağıdaki liste için map, filter, sorted gibi gömülü fonksiyonları kullanarak:
sayilar = [5, 12, 7, 18, 24, 3, 16]
# Sadece çift sayıları filtreleyin.
cift_sayilar = list(filter(lambda x: x % 2 == 0, sayilar))
print("Çift Sayılar:", cift_sayilar)

# Bu sayıların karelerini bulun.
kareleri = list(map(lambda x: x**2, cift_sayilar))
print("Kareleri:", kareleri)

#Karelerini azalan sırada sıralayın
sirali_kareleri = sorted(kareleri, reverse=True)
print("Kareleri azalan sırada:", sirali_kareleri)

Çift Sayılar: [12, 18, 24, 16]
Kareleri: [144, 324, 576, 256]
Kareleri azalan sırada: [576, 324, 256, 144]


In [18]:
#Soru 7 – Lambda İfadeleri
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
sirali=sorted(kelimeler,reverse=False,key=lambda x:len(x))
print(sirali)

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [21]:
#Soru 8 – Metodlar
strng="VeriBilimi2025"
def get_digits(strng):
  c=""
  for i in strng:
   if i.isdigit():
    i=int(i)
    c+=str(i)
  return c
get_digits(strng)
#rakamlar toplamları
print(sum([int(i) for i in get_digits(strng)]))


9


In [23]:
#Soru 9 – (Ekstra) Numpy 1
import numpy as np

# 10 elemanlı, 0–50 arasında rastgele tam sayılar
dizi = np.random.randint(0, 51, 10)
print("Dizi:", dizi)

# Ortalama
ortalama = np.mean(dizi)
# Standart sapma
std = np.std(dizi)
# En büyük değer
maks = np.max(dizi)

print("Ortalama:", ortalama)
print("Standart Sapma:", std)
print("En Büyük Değer:", maks)


Dizi: [ 9 24 10 13 47 48 29 29 10 32]
Ortalama: 25.1
Standart Sapma: 13.945967159003352
En Büyük Değer: 48


In [31]:
# Soru 10
import numpy as np

# 5x5 boyutunda, 0–1 arasında rastgele sayılar
matris = np.random.rand(5, 5)
print("Orijinal Matris:\n", matris)

# Her sütunun ortalaması
sutun_ort = np.mean(matris, axis=0)
print("\nSütun Ortalamaları:", sutun_ort)

# 0.5'ten büyükse 1, küçük/eşitse 0 yap -> binary matris
binary_matris = (matris > 0.5).astype(int)
print("\nBinary Matris:\n", binary_matris)



Orijinal Matris:
 [[0.02248388 0.99199243 0.73864258 0.18893546 0.21618991]
 [0.28580136 0.73802392 0.65497046 0.11554945 0.702599  ]
 [0.28216633 0.82725464 0.40721848 0.07015746 0.74280834]
 [0.04349158 0.60911409 0.32131488 0.94387709 0.11192669]
 [0.19894804 0.28345293 0.24968639 0.52162517 0.54856949]]

Sütun Ortalamaları: [0.16657824 0.6899676  0.47436656 0.36802893 0.46441869]

Binary Matris:
 [[0 1 1 0 0]
 [0 1 1 0 1]
 [0 1 0 0 1]
 [0 1 0 1 0]
 [0 0 0 1 1]]
